fix(features):fixed text-decoration on features
accordproject/techdocs pull request #382
Opened 2021-09-14 10:50 UTC by shubhangi013

Signed-off-by: shubhangi013 <choudharyshubhangi13@gmail.com>

# Closes #381 

The PR aims at removing the underlining effect that causes a bad-user experience because of being uneven. 
### Changes

- <ONE> added 'text-decoration: none!important;'

### Related Issues
- Issue #381 

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

2021-12-01 14:34 UTC, Michael-Grover commented
@shubhangi013 this looks good to me. It looks like some CSS has changed, so I think it would be good to have an engineer take and confirm only the intended links are affected before merging. @DianaLease @irmerk

2021-12-01 17:12 UTC, irmerk requested changes
I think the `website/package-lock.json` changes can be discarded.

2021-12-01 17:36 UTC, shubhangi013 commented
> I think the `website/package-lock.json` changes can be discarded.

Oh alright ! I'll do that :)

2021-12-01 18:45 UTC, shubhangi013 commented
Sorry for this uneven commit history, my VSCode was acting up :sweat_smile: 
Could you review it once? @irmerk

2021-12-03 12:52 UTC, shubhangi013 commented
@Michael-Grover could you have a look at it please 😅

2021-12-03 16:40 UTC, Michael-Grover commented
@shubhangi013 it looks good to me, I'm not an engineer though, so I still think it would be good to have @DianaLease or @irmerk give the final approval.

2021-12-04 12:25 UTC, shubhangi013 commented
> @shubhangi013 it looks good to me, I'm not an engineer though, so I still think it would be good to have @DianaLease or @irmerk give the final approval.

Ah right! Thankyou :)

2021-12-06 13:50 UTC, irmerk commented
You should rebase this down to one commit and correct the DCO signoff.

2021-12-06 16:09 UTC, shubhangi013 commented
> You should rebase this down to one commit and correct the DCO signoff.

done!

2021-12-07 13:44 UTC, irmerk commented
We need to check if altering `a` tags in this PR doesn't have any unintended effects on the rest of the site.

2021-12-07 18:51 UTC, shubhangi013 commented
> We need to check if altering `a` tags in this PR doesn't have any unintended effects on the rest of the site.

Oh right. I did run it locally tho and they worked fine. 😅

2021-12-21 18:21 UTC, irmerk approved these changes
Looks good from my manual review. Would like two other manual reviews from @accordproject/maintainers members.

2021-12-21 21:41 UTC, mttrbrts approved these changes

2021-12-21 23:52 UTC, dselman approved these changes

2022-01-05 10:50 UTC, merged